language: node_js

node_js:
  - "stable"

os:
  - linux
  - osx

node_js:
  - "stable"

addons:
  firefox: "latest"

install:
  - npm install -g codecov

script:
  - npm run lint:all
  - npm run test:all
  - npm run build:lint
  - codecov
